#ifndef PRE_H
#define PRE_H
#include <ncurses.h>
#include <stdio.h>
#include <arpa/inet.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <math.h>
#include <netdb.h>
#include <pthread.h>
#include <string.h>
#include <unistd.h>
#include <limits.h>
#include <time.h>
#include <signal.h>
#include <sys/types.h>
#include <sys/time.h>
#include <sys/ioctl.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <sys/stat.h>
#include <fcntl.h>
#include "buffSizes.h"
#include "client.h"
#include "server_vars.h"
#include "filePaths.h"
#include "auxFuncs.h"
#include "resource_consts.h"
#include "http_req_parser.h"
#include "http_response_aux.h"
#include "filePaths.h"
#include "io_ops.h"
#endif
